import streamlit as st
import strategist
import urllib.parse
import requests
import io
import markdown
from xhtml2pdf import pisa # CRITICAL: For PDF Generation

# 1. CONFIG
st.set_page_config(page_title="ACE Engine", page_icon="⚡", layout="wide")

# 2. THEME ENGINE
def apply_theme(theme_choice):
    if theme_choice == "Dark Mode":
        st.markdown("""<style>.stApp { background-color: #0e1117; color: white; }</style>""", unsafe_allow_html=True)
    elif theme_choice == "Light Mode":
        st.markdown("""<style>.stApp { background-color: #ffffff; color: black; }</style>""", unsafe_allow_html=True)
    elif theme_choice == "Hacker Green":
        st.markdown("""<style>.stApp { background-color: #002b36; color: #859900; } .stButton button {border: 1px solid #859900;}</style>""", unsafe_allow_html=True)

# 3. PDF GENERATOR ENGINE
def create_pdf(markdown_content):
    """
    Converts Markdown text into a styled PDF file.
    """
    # Convert MD to HTML first
    html_text = markdown.markdown(markdown_content)
    
    # Add Professional Styling
    styled_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 11pt; color: #333; }}
            h1 {{ color: #2E86C1; font-size: 24pt; text-align: center; margin-bottom: 20px; }}
            h2 {{ color: #1B4F72; font-size: 18pt; margin-top: 25px; border-bottom: 1px solid #ccc; }}
            h3 {{ color: #2874A6; font-size: 14pt; margin-top: 15px; }}
            p {{ line-height: 1.6; text-align: justify; margin-bottom: 10px; }}
            strong {{ color: #000; }}
        </style>
    </head>
    <body>
        {html_text}
        <br><br>
        <hr>
        <p style="text-align: center; font-size: 9pt; color: #888;">Generated by ACE: Automated Content Engine</p>
    </body>
    </html>
    """
    
    # Generate PDF
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(styled_html, dest=pdf_buffer)
    
    if pisa_status.err:
        return None
    return pdf_buffer.getvalue()

# 4. ROBUST IMAGE DOWNLOADER
def get_image_bytes(prompt_text):
    """
    Downloads image bytes to prevent Streamlit URL crashes.
    """
    try:
        # Simplify prompt for URL safety
        short_prompt = prompt_text[:40]
        safe_prompt = urllib.parse.quote(f"editorial photo of {short_prompt}, high quality")
        
        # Pollinations URL
        url = f"https://image.pollinations.ai/prompt/{safe_prompt}?nologo=true&width=1024&height=512"
        
        # Download strictly with timeout
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            return response.content # Return raw bytes
    except:
        pass
    return None

# 5. SIDEBAR
with st.sidebar:
    st.title("🎛️ ACE Control")
    
    theme = st.selectbox("🎨 Interface Theme", ["Default (System)", "Dark Mode", "Light Mode", "Hacker Green"])
    apply_theme(theme)
    st.divider()

    niche = st.text_input("Niche / Topic", "Artificial Intelligence")
    audience = st.text_input("Audience", "University Students")
    st.divider()
    
    btn = st.button("🚀 Auto-Pilot Launch", type="primary", use_container_width=True)

# 6. MAIN APP
st.title("⚡ ACE: Automated Content Engine")

if btn:
    with st.status("🚀 System Running...", expanded=True) as status:
        
        # 1. Strategy
        try:
            ideas = strategist.strategist_node(niche, audience)
            best_idea = ideas[0] if isinstance(ideas, list) else str(ideas)
            st.info(f"Selected Angle: {best_idea[:80]}...")
        except:
            st.error("Strategy Connection Failed. Using fallback.")
            best_idea = f"The Future of {niche} for {audience}"
            
        # 2. Architecture
        try:
            headers = strategist.architect_node(best_idea)
            st.write("Blueprint Designed.")
        except:
            headers = ["The Challenge", "The Solution", "Practical Steps", "Conclusion"]
            
        # 3. Writing
        full_article = strategist.content_factory_node(best_idea, headers)
        
        # 4. Polish
        seo_kit = strategist.polish_node(full_article)
        
        # 5. Image Generation (Download Bytes)
        st.write("🎨 Generating Visuals...")
        image_bytes = get_image_bytes(niche)
        
        status.update(label="Done!", state="complete", expanded=False)

    # 7. RESULTS DISPLAY
    
    # Display Image from Bytes (No URL Crash)
    if image_bytes:
        st.image(image_bytes, caption=f"Visual: {niche}", use_container_width=True)
    else:
        st.warning("⚠️ Image could not be generated (Network Timeout).")
        
    st.markdown(full_article)
    st.divider()
    with st.expander("View SEO Strategy Kit"):
        st.markdown(seo_kit)
    
    # 8. PDF DOWNLOAD LOGIC
    full_text_for_pdf = f"# {best_idea}\n\n" + full_article + "\n\n---\n\n" + seo_kit
    pdf_data = create_pdf(full_text_for_pdf)
    
    col1, col2 = st.columns(2)
    
    # PDF Button
    if pdf_data:
        col1.download_button(
            label="📄 Download PDF Report",
            data=pdf_data,
            file_name="ace_report.pdf",
            mime="application/pdf",
            type="primary",
            use_container_width=True
        )
    else:
        col1.error("PDF Generation Failed")
        
    # Markdown Button (Backup)
    col2.download_button(
        label="📥 Download Markdown",
        data=full_text_for_pdf,
        file_name="ace_article.md",
        mime="text/markdown",
        use_container_width=True
    )
